# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "0822df7e4a246194dfcd5bf5546a6884"
name = "test-progryss"
application_url = "https://test-progryss.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://test-progryss.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=test-progryss.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
